[package]
name = "pico-todo"
version = "0.1.0"
authors = ["Nathanial Hartman <nathanial.hartman@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono="0.4.6"
clap="2.33.0"
dirs="*"